Repository PaloAltoNetworks/terraform-azurerm-vmseries-modules, pull requests merged in 2021-05, with the labels that each got.

#99 feat: allow terraform 0.14.x on every module
  examples/bootstrap/README.md
  examples/bootstrap/versions.tf
  examples/panorama/README.md
  examples/panorama/versions.tf
  examples/transit_vnet_common/README.md
  examples/transit_vnet_common/versions.tf
  examples/vmseries_scaleset/README.md
  examples/vmseries_scaleset/versions.tf
  examples/vnet/README.md
  examples/vnet/versions.tf
  modules/bootstrap/README.md
  modules/bootstrap/versions.tf
  modules/loadbalancer/README.md
  modules/loadbalancer/versions.tf
  modules/panorama/README.md
  modules/panorama/versions.tf
  modules/vmseries/README.md
  modules/vmseries/versions.tf
  modules/vmss/README.md
  modules/vmss/versions.tf
  modules/vnet/README.md
  modules/vnet/versions.tf
Labels: feat

#97 TERRAM-92 ci: add pre-commit framework as a continuous check
  .github/workflows/ci.yml
  scripts/install.sh
  scripts/requirements.txt
  scripts/run.sh
Labels: enhancement

#102 bug: Add missing folder in bootstrap module (TERRAM-112)
  modules/bootstrap/main.tf
Labels: bug

#104 feat(examples/transit_vnet_dedicated): new example
  examples/transit_vnet_dedicated/README.md
  examples/transit_vnet_dedicated/example.tfvars
  examples/transit_vnet_dedicated/inbound_files/authcodes.sample
  examples/transit_vnet_dedicated/inbound_files/init-cfg.sample.txt
  examples/transit_vnet_dedicated/main.tf
  examples/transit_vnet_dedicated/outbound_files/authcodes.sample
  examples/transit_vnet_dedicated/outbound_files/init-cfg.sample.txt
  examples/transit_vnet_dedicated/outputs.tf
  examples/transit_vnet_dedicated/variables.tf
  examples/transit_vnet_dedicated/versions.tf
Labels: enhancement
