Repository PaloAltoNetworks/terraform-azurerm-vmseries-modules, pull requests merged in 2022-01, with the labels that each got.

#120 docs(vnet): update README of the vnet module
  modules/vnet/README.md
Labels: documentation, azure, v0.3

#129 docs: update CONTRIBUTING.md FIXES #128
  CONTRIBUTING.md
Labels: documentation, azure

#126 feat(vmseries): Allow ip_forwarding to be a variable
  modules/vmseries/README.md
  modules/vmseries/main.tf
  modules/vmseries/variables.tf
Labels: enhancement, azure, v0.3
